# .github/workflows/labeled-echo.yml

name: Labeled Echo Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: repo-build    #this job runs on github default runner
    steps:
      - name: Echo from build
        run: |
          echo "Running build job"
          sleep 60

  deploy:
    runs-on: repo-deploy
    steps:
      - name: Echo from deploy
        run: |
          echo "Running deploy job"
          sleep 60

  s8:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from s8
        run: echo "Running s8 job"

  s9:
    runs-on: s8
    steps:
      - name: Echo from s9
        run: |
          echo "Running s9 job"
          sleep 60