# # .github/workflows/simple-ci.yml
# name: CI Workflow
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build_image_and_push_into_dockerhub:
#     name: Build image and push to DockerHub
#     runs-on: [self-hosted, repo-build]
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Debug Docker info
#         run: |
#           docker --version
#           sudo docker info

#       - name: Docker login
#         run: |
#           echo "Logging into Docker Hub..."
#           echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
#           echo "Login successful"

#       - name: Verify login
#         run: |
#           sudo docker info | grep Username || echo "Login verification failed"

#       - name: Build Docker image
#         run: |
#           IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/app01
#           IMAGE_TAG=latest
#           echo "Building Docker image: $IMAGE_NAME:$IMAGE_TAG"
#           sudo docker build -t $IMAGE_NAME:$IMAGE_TAG s9/app01
#           echo "Build completed successfully"

#       - name: Verify image exists
#         run: |
#           IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/app01
#           sudo docker images | grep $IMAGE_NAME

#       - name: Push Docker image
#         run: |
#           IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/app01
#           IMAGE_TAG=latest
#           echo "Pushing Docker image: $IMAGE_NAME:$IMAGE_TAG"
#           sudo docker push $IMAGE_NAME:$IMAGE_TAG



# .github/workflows/simple-ci.yml
name: CI Workflow
on:
  push:
    branches:
      - main
jobs:
  build_image_and_push_into_dockerhub:
    name: Build image and push to DockerHub
    runs-on: [self-hosted, repo-build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Debug Docker info
        run: |
          docker --version
          sudo docker info
      - name: Docker login
        run: |
          echo "Logging into Docker Hub..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          echo "Login successful"
      - name: Verify login
        run: |
          sudo docker info | grep Username || echo "Login verification failed"
      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/app01
          IMAGE_TAG=latest
          echo "Building Docker image: $IMAGE_NAME:$IMAGE_TAG"
          sudo docker build -f s9/app01/api.Dockerfile -t $IMAGE_NAME:$IMAGE_TAG s9/app01
          echo "Build completed successfully"
      - name: Verify image exists
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/app01
          sudo docker images | grep $IMAGE_NAME
      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/app01
          IMAGE_TAG=latest
          echo "Pushing Docker image: $IMAGE_NAME:$IMAGE_TAG"
          sudo docker push $IMAGE_NAME:$IMAGE_TAG