name:  Series Pipeline            #Uses one runner as defined on "runs-on"

on: [push]

jobs:
  setup:
    name: Setup Job
    runs-on: repo-deploy
    steps:
      - name: Setup environment
        run: |
          echo "🔧 Setting up environment..."
          sleep 30

  build:
    name: Build Job
    runs-on: repo-deploy
    needs: setup
    steps:
      - name: Build application
        run: |
          echo "🏗️ Building the application..."
          sleep 30

  test:
    name: Test Job
    runs-on: repo-deploy
    needs: build
    steps:
      - name: Run tests
        run: |
          echo "🧪 Running tests..."
          sleep 30

  scan:
    name: Scan Job
    runs-on: repo-deploy
    needs: test
    steps:
      - name: Security scan
        run: |
          echo "🔍 Performing security scan..."
          sleep 30

  deploy:
    name: Deploy Job
    runs-on: repo-deploy
    needs: scan
    steps:
      - name: Deploy application
        run: |
          echo "🚀 Deploying application..."
          sleep 30




# Job dependencies with needs.

# Uses one runner

# Clear job naming and flow.

# Simulated time delays (sleep) for each job step.

# CI/CD structure mirroring real pipelines.

# Jobs run in sequence
# Emulates real CI/CD order
# Slower but more controlled