name: Multi Job Parallel       # Executed. uses multiple runners or each job has a runner as defined in "runs-on", builds same time

on: [push]

jobs:
  setup:
    name: Setup Job
    runs-on: repo-deploy
    steps:
      - name: Setup environment
        run: |
          echo "🔧 Setting up environment..."
          sleep 30

  build:
    name: Build Job
    runs-on: repo-build
    steps:
      - name: Build application
        run: |
          echo "🏗️ Building the application..."
          sleep 30

  test:
    name: Test Job
    runs-on: s9
    steps:
      - name: Run tests
        run: |
          echo "🧪 Running tests..."
          sleep 30

  scan:
    name: Scan Job
    runs-on: ubuntu-latest
    steps:
      - name: Security scan
        run: |
          echo "🔍 Performing security scan..."
          sleep 30

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: |
          echo "🚀 Deploying application..."
          sleep 30



# Jobs run in parallel, building at the same time
# Useful for independent tasks
# Faster but no coordination