name: Multi Job Parallel               #uses multiple runners or one as defined in "runs-on", builds same time

on: [push]

jobs:
  setup:
    name: Setup Job
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          echo "🔧 Setting up environment..."
          sleep 2

  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run: |
          echo "🏗️ Building the application..."
          sleep 2

  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo "🧪 Running tests..."
          sleep 2

  scan:
    name: Scan Job
    runs-on: ubuntu-latest
    steps:
      - name: Security scan
        run: |
          echo "🔍 Performing security scan..."
          sleep 2

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: |
          echo "🚀 Deploying application..."
          sleep 2



# Jobs run in parallel, building at the same time
# Useful for independent tasks
# Faster but no coordination