name: Mixed Series and Parallel Workflow

on: [push]

jobs:
  # 1. Setup (runs first)
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "🔧 Installing dependencies..."
          sleep 2

  # 2. Parallel jobs (run after setup)
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run unit tests
        run: |
          echo "🧪 Running tests..."
          sleep 2

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run linter
        run: |
          echo "🧹 Linting code..."
          sleep 2

  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run scan
        run: |
          echo "🔍 Running security scan..."
          sleep 2

  # 3. Deploy (runs after all 3 above complete)
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [test, lint, scan]
    steps:
      - name: Deploy
        run: |
          echo "🚀 Deploying application..."
          sleep 2
